networks:
  app-net:
    driver: bridge

services:
  eureka-server:
    networks:
      - app-net
    build: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka

  hello-service:
    networks:
      - app-net
    depends_on:
      - eureka-server
    build: hello-service
    ports:
      - "8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka

  api-gateway:
    networks:
      - app-net
    depends_on:
      - eureka-server
      - hello-service
    build: api-gateway
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka