server:
  port: 0

spring:
  application:
    name: hello-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
